# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kiwi Huts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kiwi Huts
pod 'Firebase/Firestore'

end

target 'Kiwi HutsTests' do
  inherit! :search_paths
  
end
