name: Update Hut Data

on:
  schedule:
    - cron: "45 9,21 * * *" # 09:05, 21:45 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python Backend/main.py
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
          DOC_API_KEY: ${{ secrets.DOC_API_KEY }}
