name: Update Hut Data

on:
  schedule:
    - cron: "30 21 * * *" # Runs at 21:30 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        run: python Backend/main.py
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
          DOC_API_KEY: ${{ secrets.DOC_API_KEY }}

      - name: Commit and push error.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f error.txt
          git commit -m "Add error.txt" -a
          git push
