name: Update Hut Data

on:
  schedule:
    - cron: "45 10,22 * * *" # 10:05, 22:45 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Firebase key file
        run: echo "$FIREBASE_JSON" > firebase_key.json
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}

      - name: Run script
        run: python Backend/main.py
        env:
          FIREBASE_JSON: firebase_key.json
          DOC_API_KEY: ${{ secrets.DOC_API_KEY }}
